### ISSUE TITLE
-a command-line option?

### ISSUE THREAD

**Issue by GolfingSuccess** [DennisMitchell/sesos#2]
I don't think you have given clear documentation as to what `-a` exactly means. I tried using it, but what I got was that the output was suppressed.

**Comment by DennisMitchell** [comment]
You use `sesos -a program` to assemble your source code, where `program.sasm` is your Sesos assembly file, creating the Sesos binary file `program.sbin`. Once assembled, you use `sesos program` to execute it.

The online interpreter assembles and executed in one step, so you shouldn't use the `-a` flag there.

**Comment by GolfingSuccess** [comment]
@DennisMitchell Oh, thanks for the information. Yes, I was using TIO.
